migrate(app => {
const access = "@request.auth.id != '' && @request.auth.collectionName = 'users' && @request.auth.disabled = false";
const rel = (name, table) => ({name, type:'relation', collectionId:app.findCollectionByNameOrId(table).id, maxSelect:1, cascadeDelete:false});
const stamp = () => [rel('created_by','users'),rel('updated_by','users'),{name:'revision',type:'number',onlyInt:true,min:1,required:true},{name:'created',type:'autodate',onCreate:true},{name:'updated',type:'autodate',onCreate:true,onUpdate:true}];
app.save(new Collection({name:'team_members',type:'base',fields:[rel('account','users'),{name:'is_admin',type:'bool'}],indexes:['CREATE UNIQUE INDEX idx_team_account ON team_members (account)']}));
app.save(new Collection({name:'user_directory',type:'base',fields:[{name:'name',type:'text',required:true,max:200}]}));
app.save(new Collection({name:'counters',type:'base',fields:[{name:'key',type:'text',required:true},{name:'value',type:'number',onlyInt:true}],indexes:['CREATE UNIQUE INDEX idx_counter_key ON counters (key)']}));

app.save(new Collection({name:'conversations',type:'base',listRule:null,viewRule:null,createRule:access,updateRule:access,deleteRule:null,fields:[{"name": "kind", "type": "select", "values": ["public_channel", "private_channel", "dm", "support"], "maxSelect": 1, "required": true},{"name": "title", "type": "text", "max": 200},rel('visitor','users'),rel('assignee','users'),{"name": "status", "type": "select", "values": ["open", "resolved"], "maxSelect": 1, "required": true},{"name": "archived", "type": "bool"}].concat(stamp()),indexes:[]}));
app.save(new Collection({name:'memberships',type:'base',listRule:null,viewRule:null,createRule:access,updateRule:access,deleteRule:null,fields:[rel('conversation','conversations'),rel('account','users'),{"name": "active", "type": "bool"}].concat(stamp()),indexes:["CREATE UNIQUE INDEX idx_membership ON memberships (conversation,account)"]}));
app.save(new Collection({name:'messages',type:'base',listRule:null,viewRule:null,createRule:access,updateRule:access,deleteRule:null,fields:[rel('conversation','conversations'),{"name": "parent", "type": "text", "max": 200},{"name": "body", "type": "text", "max": 20000},{"name": "internal", "type": "bool"},{"name": "deleted", "type": "bool"},{"name": "mentions", "type": "json", "maxSize": 1048576},rel('author','users')].concat(stamp()),indexes:["CREATE INDEX idx_message_conversation ON messages (conversation,created)", "CREATE INDEX idx_message_parent ON messages (parent)"]}));
app.save(new Collection({name:'attachments',type:'base',listRule:null,viewRule:"@request.context = 'protectedFile' && ("+access+")",createRule:access,updateRule:access,deleteRule:null,fields:[rel('message','messages'),{"name": "original", "type": "file", "maxSize": 26214400, "maxSelect": 1, "required": true, "protected": true},{"name": "sha256", "type": "text", "max": 200},rel('author','users')].concat(stamp()),indexes:[]}));
app.save(new Collection({name:'reactions',type:'base',listRule:null,viewRule:null,createRule:access,updateRule:access,deleteRule:null,fields:[rel('message','messages'),rel('account','users'),{"name": "emoji", "type": "text", "max": 200},{"name": "active", "type": "bool"}].concat(stamp()),indexes:["CREATE UNIQUE INDEX idx_reaction ON reactions (message,account,emoji)"]}));
app.save(new Collection({name:'read_receipts',type:'base',listRule:null,viewRule:null,createRule:access,updateRule:access,deleteRule:null,fields:[rel('message','messages'),rel('account','users')].concat(stamp()),indexes:["CREATE UNIQUE INDEX idx_receipt ON read_receipts (message,account)"]}));
app.save(new Collection({name:'inbox',type:'base',listRule:null,viewRule:null,createRule:null,updateRule:null,deleteRule:null,fields:[rel('account','users'),rel('message','messages'),{"name": "reason", "type": "select", "values": ["mention", "reply"], "maxSelect": 1, "required": true}].concat([{name:'created',type:'autodate',onCreate:true}]),indexes:["CREATE UNIQUE INDEX idx_inbox ON inbox (account,message,reason)"]}));
app.save(new Collection({name:'changes',type:'base',listRule:null,viewRule:null,createRule:null,updateRule:null,deleteRule:null,fields:[{"name": "seq", "type": "number", "onlyInt": true, "min": 1, "max": 9007199254740991},{"name": "collection", "type": "text", "max": 200},{"name": "record", "type": "text", "max": 200},{"name": "conversation", "type": "text", "max": 200},{"name": "message", "type": "text", "max": 200},{"name": "internal", "type": "bool"},{"name": "action", "type": "text", "max": 200}].concat([{name:'created',type:'autodate',onCreate:true}]),indexes:["CREATE UNIQUE INDEX idx_change_seq ON changes (seq)"]}));
app.save(new Collection({name:'audit_log',type:'base',listRule:null,viewRule:null,createRule:null,updateRule:null,deleteRule:null,fields:[{"name": "collection", "type": "text", "max": 200},{"name": "record", "type": "text", "max": 200},{"name": "conversation", "type": "text", "max": 200},{"name": "message", "type": "text", "max": 200},{"name": "internal", "type": "bool"},{"name": "actor", "type": "text", "max": 200},{"name": "action", "type": "text", "max": 200},{"name": "changes", "type": "json", "maxSize": 1048576}].concat([{name:'created',type:'autodate',onCreate:true}]),indexes:[]}));
const s=app.settings();s.batch.enabled=true;s.batch.maxRequests=100;s.batch.timeout=10;app.save(s);
},()=>{throw new Error('Restore a verified complete backup to roll back initial schema');});
